### ISSUE TITLE
使用@CopyProperty拷贝Enum会抛出BeanCopyException

### ISSUE THREAD

**Issue by wjjboy** [yangtu222/BeanUtils#18]
以下实体类

public enum Enum {
    A,B,C;
}

`@Data`
public class Inside{
    private String a;
    private Enum b;
}

`@Data`
public class FromBean {
    private String c;
    private Inside inside;
}

`@Data`
@BeanCopySource(source=FromBean.class)
public class ToBean {

    @CopyProperty(property = "inside.a")
    private String a;

    @CopyProperty(property = "inside.b")
    private Enum b;

    private String c;
}

使用copyBean
ToBean toBean = BeanCopyUtils.copyBean(fromBean, ToBean.class);

会抛出如下异常
com.tuyang.beanutils.exception.BeanCopyException: beanCopy new instance

	at com.tuyang.beanutils.internal.utils.InstanceUtils.newInstance(InstanceUtils.java:113)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:198)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:135)
	at cn.com.business.BeanCopyTest.test(BeanCopyTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoSuchMethodException: cn.com.business.BeanCopyTest$ToBean.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.tuyang.beanutils.internal.utils.InstanceUtils.newInstance(InstanceUtils.java:108)
	... 25 more

看异常的描述是枚举类没有构造方法，比较奇怪的是枚举类的拷贝不是应该是直接set的formBean.getInside().getB()的吗？为什么是还要new一个enum的。
然后对于CopyProperty拷贝enum有什么解决方案嘛？

**Comment by yangtu222** [comment]
hi，这个地方不是new enum的问题，是在通过ToBean.class创建ToBean实例时候出的问题。可能是你ToBean的访问权限，或者构造函数没有遵循JavaBean的方式造成的，比如构造函数没有缺省构造函数，而是带参数的那种。临时解决办法为：
ToBean toBean = BeanCopyUtils.copyBean(fromBean, new ToBean(XXX) );
其中new ToBean(XXX)这儿，是你ToBean的构造函数和参数设置。

**Comment by wjjboy** [comment]
改成 ToBean toBean = (ToBean)BeanCopyUtils.copyBean(fromBean, new ToBean());
依旧是出现下图的exception,麻烦帮忙看下问题，谢谢。
![qq 20190211100318](https://user-images.githubusercontent.com/14308166/52543360-1b942d80-2de4-11e9-9a51-5f7ab552d53f.png)

**Comment by wjjboy** [comment]
> hi，这个地方不是new enum的问题，是在通过ToBean.class创建ToBean实例时候出的问题。可能是你ToBean的访问权限，或者构造函数没有遵循JavaBean的方式造成的，比如构造函数没有缺省构造函数，而是带参数的那种。临时解决办法为：
> ToBean toBean = BeanCopyUtils.copyBean(fromBean, new ToBean(XXX) );
> 其中new ToBean(XXX)这儿，是你ToBean的构造函数和参数设置。



> hi，这个地方不是new enum的问题，是在通过ToBean.class创建ToBean实例时候出的问题。可能是你ToBean的访问权限，或者构造函数没有遵循JavaBean的方式造成的，比如构造函数没有缺省构造函数，而是带参数的那种。临时解决办法为：
> ToBean toBean = BeanCopyUtils.copyBean(fromBean, new ToBean(XXX) );
> 其中new ToBean(XXX)这儿，是你ToBean的构造函数和参数设置。

ToBean就是我一开始贴出来类，可以直接new对象的并不会报错

**Comment by wjjboy** [comment]
> hi，这个地方不是new enum的问题，是在通过ToBean.class创建ToBean实例时候出的问题。可能是你ToBean的访问权限，或者构造函数没有遵循JavaBean的方式造成的，比如构造函数没有缺省构造函数，而是带参数的那种。临时解决办法为：
> ToBean toBean = BeanCopyUtils.copyBean(fromBean, new ToBean(XXX) );
> 其中new ToBean(XXX)这儿，是你ToBean的构造函数和参数设置。

我在com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:198)打了个断点如下图，看出来应该是进入了enum的拷贝时报错了。
![qq 20190211100955](https://user-images.githubusercontent.com/14308166/52543525-4e8af100-2de5-11e9-8daf-df5fc85b4a2b.png)

我调试看了下JavassistBeanCopyFactory生成出来的BeanCopier
![qq 20190211102943](https://user-images.githubusercontent.com/14308166/52543834-c2c69400-2de7-11e9-8018-9d6783e754d5.jpg)
最后拼接出来的sb字符串是
### {
    cn.com.aalib.business.BeanCopyTest$FromBean source = (cn.com.aalib.business.BeanCopyTest$FromBean) $1;
    cn.com.aalib.business.BeanCopyTest$ToBean target = (cn.com.aalib.business.BeanCopyTest$ToBean) $2;
    if( source.getInside() != null  ) { 
       target.setA( source.getInside().getA() );
    }
    if( source.getInside() != null  ) { 
       target.setB( (cn.com.aalib.business.BeanCopyTest$Enum) com.tuyang.beanutils.BeanCopyUtils.copyBean( source.getInside().getB(), cn.com.aalib.business.BeanCopyTest$Enum.class ) );
    }
    target.setC( source.getC() );
    return target;
}
看得出对于b属性的映射是调用BeanCopyUtils.copyBean(source.getInside().getB(), Enum.class);
这边生成字符串的具体策略没看，我理解下来是不是能对enum做特殊处理。然后生成出来copy规则应该是像string这样 target.setB( source.getInside().getB() ); 就可以？

**Comment by yangtu222** [comment]
问题已找到，需要对enum单独处理。

**Comment by yangtu222** [comment]
1.0.10 发布，fix这个问题。

**Comment by wjjboy** [comment]
> 1.0.10 发布，fix这个问题。

已经使用新版本解决了该问题，非常感谢。
